# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

  user = User.create(email: "michael@gmail.com", username: "mag42c", password: "mag42c84", password_confirmation: "mag42c84")
  user1 = User.create(email: "test@test.com", username: "mike", password: "mag42c84", password_confirmation: "mag42c84")
  user3 = User.create(email: "tester@test.com", username: "jessie", password: "mag42c84", password_confirmation: "mag42c84")

  book1 = Book.create(title: "Area 51", author: "Anne Jacobsen", genre: "non-fiction", good_reads_id: 11305364,checked_out?: false)
  book2 = Book.create(title: "The Corrections", author: "Jonathan Frazen", genre: "fiction", good_reads_id: 3805, checked_out?: false)
  book3 = Book.create(title: "Aftershock", author: "Robert Reich", genre: "non-fiction", good_reads_id: 7845023, checked_out?: false)
  book4 = Book.create(title: "Bleeding Edge", author: "Thomas Pychon", genre: "fiction", good_reads_id: 17208457, checked_out?: false)
  book5 = Book.create(title: "The Naked and the Dead", author: "Norman Mailer", genre: "fiction", good_reads_id: 12467, checked_out?: false)
  book6 = Book.create(title: "Libra", author: "Don Dello", genre: "fiction", good_reads_id: 400, checked_out?: false)
  book7 = Book.create(title: "Area 51", author: "Anne Jacobsen", genre: "non-fiction", checked_out?: false)
  book8 = Book.create(title: "The Corrections", author: "Jonathan Frazen", genre: "fiction", checked_out?: false)
  book9 = Book.create(title: "Aftershock", author: "Robert Reich", genre: "non-fiction", checked_out?: false)
  book10 = Book.create(title: "Bleeding Edge", author: "Thomas Pychon", genre: "fiction", checked_out?: false)
  book11 = Book.create(title: "The Naked and the Dead", author: "Norman Mailer", genre: "fiction", checked_out?: false)
  book12 = Book.create(title: "Libra", author: "Don Dello", genre: "fiction", checked_out?: false)
  book13 = Book.create(title: "Area 51", author: "Anne Jacobsen", genre: "non-fiction", checked_out?: false)
  book14 = Book.create(title: "The Corrections", author: "Jonathan Frazen", genre: "fiction", checked_out?: false)
  book15 = Book.create(title: "Aftershock", author: "Robert Reich", genre: "non-fiction", checked_out?: false)
  book16 = Book.create(title: "Bleeding Edge", author: "Thomas Pychon", genre: "fiction", checked_out?: false)
  book17 = Book.create(title: "The Naked and the Dead", author: "Norman Mailer", genre: "fiction", checked_out?: false)
  book18 = Book.create(title: "Libra", author: "Don Dello", genre: "fiction", checked_out?: false)
  book19 = Book.create(title: "Area 51", author: "Anne Jacobsen", genre: "non-fiction", checked_out?: false)
  book20 = Book.create(title: "The Corrections", author: "Jonathan Frazen", genre: "fiction", checked_out?: false)
  book21 = Book.create(title: "Aftershock", author: "Robert Reich", genre: "non-fiction", checked_out?: false)
  book22 = Book.create(title: "Bleeding Edge", author: "Thomas Pychon", genre: "fiction", checked_out?: false)
  book23 = Book.create(title: "The Naked and the Dead", author: "Norman Mailer", genre: "fiction", checked_out?: false)
  book24 = Book.create(title: "Libra", author: "Don Dello", genre: "fiction", checked_out?: false)
  boo25 = Book.create(title: "Area 51", author: "Anne Jacobsen", genre: "non-fiction", checked_out?: false)
  book26 = Book.create(title: "The Corrections", author: "Jonathan Frazen", genre: "fiction", checked_out?: false)
  book27 = Book.create(title: "Aftershock", author: "Robert Reich", genre: "non-fiction", checked_out?: false)
  book28 = Book.create(title: "Bleeding Edge", author: "Thomas Pychon", genre: "fiction", checked_out?: false)
  book29 = Book.create(title: "The Naked and the Dead", author: "Norman Mailer", genre: "fiction", checked_out?: false)
  book30 = Book.create(title: "Libra", author: "Don Dello", genre: "fiction", checked_out?: false)
  book31 = Book.create(title: "Area 51", author: "Anne Jacobsen", genre: "non-fiction", checked_out?: false)
  book32 = Book.create(title: "The Corrections", author: "Jonathan Frazen", genre: "fiction", checked_out?: false)
  book33 = Book.create(title: "Aftershock", author: "Robert Reich", genre: "non-fiction", checked_out?: false)
  book34 = Book.create(title: "Bleeding Edge", author: "Thomas Pychon", genre: "fiction", checked_out?: false)
  book35 = Book.create(title: "The Naked and the Dead", author: "Norman Mailer", genre: "fiction", checked_out?: false)
  book36 = Book.create(title: "Libra", author: "Don Dello", genre: "fiction", checked_out?: false)
  book37 = Book.create(title: "Area 51", author: "Anne Jacobsen", genre: "non-fiction", checked_out?: false)
  book38 = Book.create(title: "The Corrections", author: "Jonathan Frazen", genre: "fiction", checked_out?: false)
  book39 = Book.create(title: "Aftershock", author: "Robert Reich", genre: "non-fiction", checked_out?: false)
  book40 = Book.create(title: "Bleeding Edge", author: "Thomas Pychon", genre: "fiction", checked_out?: false)
  book41 = Book.create(title: "The Naked and the Dead", author: "Norman Mailer", genre: "fiction", checked_out?: false)
  book42 = Book.create(title: "Libra", author: "Don Dello", genre: "fiction", checked_out?: false)
  book43 = Book.create(title: "Area 51", author: "Anne Jacobsen", genre: "non-fiction", checked_out?: false)
  book44 = Book.create(title: "The Corrections", author: "Jonathan Frazen", genre: "fiction", checked_out?: false)
  book45 = Book.create(title: "Aftershock", author: "Robert Reich", genre: "non-fiction", checked_out?: false)
  book46 = Book.create(title: "Bleeding Edge", author: "Thomas Pychon", genre: "fiction", checked_out?: false)
  book47 = Book.create(title: "The Naked and the Dead", author: "Norman Mailer", genre: "fiction", checked_out?: false)
  book48 = Book.create(title: "Libra", author: "Don Dello", genre: "fiction", checked_out?: false)
  book49 = Book.create(title: "Area 51", author: "Anne Jacobsen", genre: "non-fiction", checked_out?: false)
  book50 = Book.create(title: "The Corrections", author: "Jonathan Frazen", genre: "fiction", checked_out?: false)
  book51 = Book.create(title: "Aftershock", author: "Robert Reich", genre: "non-fiction", checked_out?: false)
  book52 = Book.create(title: "Bleeding Edge", author: "Thomas Pychon", genre: "fiction", checked_out?: false)
  book53 = Book.create(title: "The Naked and the Dead", author: "Norman Mailer", genre: "fiction", checked_out?: false)
  book54 = Book.create(title: "Libra", author: "Don Dello", genre: "fiction", checked_out?: false)
  book55 = Book.create(title: "Area 51", author: "Anne Jacobsen", genre: "non-fiction", checked_out?: false)
  book56 = Book.create(title: "The Corrections", author: "Jonathan Frazen", genre: "fiction", checked_out?: false)
  book57 = Book.create(title: "Aftershock", author: "Robert Reich", genre: "non-fiction", checked_out?: false)
  book58 = Book.create(title: "Bleeding Edge", author: "Thomas Pychon", genre: "fiction", checked_out?: false)
  book59 = Book.create(title: "The Naked and the Dead", author: "Norman Mailer", genre: "fiction", checked_out?: false)
  book60 = Book.create(title: "Libra", author: "Don Dello", genre: "fiction", checked_out?: false)
  book61 = Book.create(title: "Area 51", author: "Anne Jacobsen", genre: "non-fiction", checked_out?: false)
  book62 = Book.create(title: "The Corrections", author: "Jonathan Frazen", genre: "fiction", checked_out?: false)
  book63 = Book.create(title: "Aftershock", author: "Robert Reich", genre: "non-fiction", checked_out?: false)
  book64 = Book.create(title: "Bleeding Edge", author: "Thomas Pychon", genre: "fiction", checked_out?: false)
  book65 = Book.create(title: "The Naked and the Dead", author: "Norman Mailer", genre: "fiction", checked_out?: false)
  book66 = Book.create(title: "Libra", author: "Don Dello", genre: "fiction", checked_out?: false)

  #checkout = Checkout.create(user_id: 1, book_id: 1, start_date: "4/12/2014", due_date: "5/12/2014")
  #checkout1 = Checkout.create(user_id: 2, book_id: 2, start_date: "4/12/2014", due_date: "5/12/2014")
  #checkout2 = Checkout.create(user_id: 3, book_id: 3, start_date: "4/12/2014", due_date: "5/12/2014")
  #checkout3 = Checkout.create(user_id: 1, book_id: 3, start_date: "4/12/2014", due_date: "5/12/2014")
